version: '3.8'

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Optional: Mount init script - uncomment if using init.sql
      # - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-webappdb}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-webappdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Service (GoLang/Gin)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy # Wait for DB to be ready
    volumes:
      - uploads_data:/app/uploads # Mount volume for image uploads
      # Optional: Mount source code for development (hot-reloading setup needed in Go)
      # - ./src/backend:/app
    environment:
      GIN_MODE: ${GIN_MODE:-release} # Use 'debug' for development
      PORT: ${BACKEND_PORT:-8080}
      DATABASE_URL: "postgres://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-webappdb}?sslmode=disable"
      JWT_SECRET: a-very-secret-key # CHANGE THIS IN PRODUCTION
      # Add other backend env vars as needed (e.g., CORS origins)
      UPLOAD_DIR: /app/uploads # Path inside the container
    networks:
      - app-network
    # Expose port only within the Docker network, Nginx will handle external access
    # expose:
    #   - "${BACKEND_PORT:-8080}"

  # Web Server / Reverse Proxy (Nginx)
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      # Expose port 80 (HTTP) - Map host port 8000 to container port 80
      - "${NGINX_PORT:-8000}:80"
      # Optional: Expose port 443 (HTTPS) - Requires SSL certificate setup
      # - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Optional: Mount SSL certificates
      # - ./path/to/certs:/etc/nginx/certs:ro
    networks:
      - app-network

# Define the dedicated network
networks:
  app-network:
    driver: bridge

# Define persistent volumes
volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local # Stores uploaded images persistently
