version: '3.8'

services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount init script to create database schema
      - ./src/backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: webappdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  # Backend Service (GoLang/Gin)
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend_app
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - uploads_data:/app/uploads # Mount volume for image uploads
      # Optional: Mount source code for development (hot-reloading setup needed in Go)
      # - ./src/backend:/app
    environment:
      GIN_MODE: release # Use 'debug' for development
      PORT: 8000
      DATABASE_URL: "postgres://user:password@db:5432/webappdb?sslmode=disable"
      JWT_SECRET: your-secret-key # CHANGE THIS IN PRODUCTION
      # Add other backend env vars as needed (e.g., CORS origins)
      UPLOAD_DIR: /app/uploads # Path inside the container
    networks:
      - app-network
    ports:
      - "8000:8000"

  # Frontend Service
  frontend:
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# Define persistent volumes
volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local # Stores uploaded images persistently
